### ISSUE TITLE
Did you have resolved this problem? The web address：https://github.com/agershun/alasql/issues/950

### ISSUE THREAD

**Issue by cag2050** [lzzattack/vueCli#1]
Did you have resolved this problem? The web address： https://github.com/agershun/alasql/issues/950

**Comment by Lxiaoacheng** [comment]
Not yet

**Comment by cag2050** [comment]
Finally, I use js-xlsx to export .xlsx file, demo: https://github.com/cag2050/vue_tables_xlsx_demo
